name: Deploy Action Code

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'dist/*.js' ]

jobs:
  deploy-action-code:
    name: Deploy Action Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: ./.github/actions/generate-action-code
      - name: Configure repository
        env:
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
        run: |
          git config user.name "${BOT_USERNAME}"
          git config user.email "${BOT_USERNAME}@users.noreply.github.com"
      - name: Commit changes
        run: |
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m '[AUTO] Update generated code'
            git push
          fi
