name: Deploy Action Code

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/*.js' ]

jobs:
  deploy-action-code:
    name: Deploy Action Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: 'npm'
      - name: Install dependencies
        run: sudo npm i -g typescript @vercel/ncc
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Generate action code
        run: npm run deploy
      - name: Configure repository
        env:
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
        run: |
          git config user.name "${BOT_USERNAME}"
          git config user.email "${BOT_USERNAME}@users.noreply.github.com"
      - name: Commit changes
        run: |
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m '[AUTO] Update generated code'
            git push
          fi
